services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  price_app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  pg_data:
